import { useEffect, useState } from 'react';
import { Navigate, useNavigate } from 'react-router-dom';
import adminApi from '../api/adminClient';
import { mediaUrl, timeAgo } from '../api/client';
import styles from './Admin.module.css';

interface Stats{users_count:number;posts_count:number;comments_count:number;likes_count:number;messages_count:number}
interface AdminUser{id:number;username:string;email:string;full_name:string|null;avatar_url:string|null;created_at:string;posts_count:number}
interface AdminPost{id:number;user:{id:number;username:string};image_url:string;caption:string|null;likes_count:number;comments_count:number;created_at:string}
type Tab='dashboard'|'users'|'posts';

export default function Admin(){
  const navigate=useNavigate(); const [tab,setTab]=useState<Tab>('dashboard'); const [stats,setStats]=useState<Stats|null>(null); const [users,setUsers]=useState<AdminUser[]>([]); const [posts,setPosts]=useState<AdminPost[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true);
  const token=localStorage.getItem('admin_token');
  const load=async()=>{setLoading(true);try{const [s,u,p]=await Promise.all([adminApi.get<Stats>('/stats'),adminApi.get<AdminUser[]>('/users'),adminApi.get<AdminPost[]>('/posts')]);setStats(s.data);setUsers(u.data);setPosts(p.data)}finally{setLoading(false)}};
  useEffect(()=>{if(token)load()},[]);
  if(!token)return <Navigate to="/admin/login" replace/>;
  const removeUser=async(user:AdminUser)=>{if(!confirm(`${user.username} 회원을 탈퇴 처리할까요? 관련 게시물과 활동도 모두 삭제됩니다.`))return;await adminApi.delete(`/users/${user.id}`);setUsers(v=>v.filter(x=>x.id!==user.id));await load()};
  const removePost=async(post:AdminPost)=>{if(!confirm(`${post.user.username}의 게시물을 삭제할까요?`))return;await adminApi.delete(`/posts/${post.id}`);setPosts(v=>v.filter(x=>x.id!==post.id));await load()};
  const logout=()=>{localStorage.removeItem('admin_token');navigate('/admin/login')};
  const filteredUsers=users.filter(u=>(u.username+' '+u.email+' '+(u.full_name||'')).toLowerCase().includes(query.toLowerCase()));
  const filteredPosts=posts.filter(p=>(p.user.username+' '+(p.caption||'')).toLowerCase().includes(query.toLowerCase()));
  return <div className={styles.adminPage}><aside><div className={styles.logo}><span>A</span><div><strong>Instagram</strong><small>ADMIN</small></div></div><nav><button className={tab==='dashboard'?styles.active:''} onClick={()=>setTab('dashboard')}>▦ 대시보드</button><button className={tab==='users'?styles.active:''} onClick={()=>setTab('users')}>♙ 회원 관리</button><button className={tab==='posts'?styles.active:''} onClick={()=>setTab('posts')}>▧ 게시물 관리</button></nav><div className={styles.asideBottom}><a href="/">서비스 보기</a><button onClick={logout}>로그아웃</button></div></aside><main><header><div><h1>{tab==='dashboard'?'대시보드':tab==='users'?'회원 관리':'게시물 관리'}</h1><p>서비스 현황과 콘텐츠를 안전하게 관리하세요.</p></div><button className={styles.refresh} onClick={load}>↻ 새로고침</button></header>{loading?<div className={styles.loading}>데이터를 불러오는 중...</div>:<>{tab==='dashboard'&&stats&&<><div className={styles.cards}><Stat label="전체 회원" value={stats.users_count} color="blue"/><Stat label="전체 게시물" value={stats.posts_count} color="violet"/><Stat label="전체 댓글" value={stats.comments_count} color="green"/><Stat label="전체 좋아요" value={stats.likes_count} color="red"/><Stat label="전체 메시지" value={stats.messages_count} color="amber"/></div><section className={styles.panel}><h2>최근 가입 회원</h2><UserTable users={users.slice(0,5)} onDelete={removeUser}/></section></>}{tab==='users'&&<section className={styles.panel}><div className={styles.panelHead}><h2>회원 목록 <span>{users.length}</span></h2><input placeholder="아이디, 이메일, 이름 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><UserTable users={filteredUsers} onDelete={removeUser}/></section>}{tab==='posts'&&<section className={styles.panel}><div className={styles.panelHead}><h2>게시물 목록 <span>{posts.length}</span></h2><input placeholder="작성자, 캡션 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className={styles.postGrid}>{filteredPosts.map(post=><article key={post.id}><img src={mediaUrl(post.image_url)} alt=""/><div><strong>@{post.user.username}</strong><p>{post.caption||'캡션 없음'}</p><small>좋아요 {post.likes_count} · 댓글 {post.comments_count} · {timeAgo(post.created_at)}</small><button onClick={()=>removePost(post)}>게시물 삭제</button></div></article>)}</div></section>}</>}</main></div>
}
function Stat({label,value,color}:{label:string;value:number;color:string}){return <div className={`${styles.stat} ${styles[color]}`}><span>{label}</span><strong>{value.toLocaleString()}</strong></div>}
function UserTable({users,onDelete}:{users:AdminUser[];onDelete:(u:AdminUser)=>void}){return <div className={styles.tableWrap}><table><thead><tr><th>회원</th><th>이메일</th><th>가입 날짜</th><th>게시물</th><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><div className={styles.userCell}>{u.avatar_url?<img src={mediaUrl(u.avatar_url)} alt=""/>:<span>{u.username[0]}</span>}<div><strong>{u.username}</strong><small>{u.full_name}</small></div></div></td><td>{u.email}</td><td>{new Date(u.created_at).toLocaleDateString('ko-KR')}</td><td>{u.posts_count}</td><td><button className={styles.danger} onClick={()=>onDelete(u)}>탈퇴</button></td></tr>)}</tbody></table>{!users.length&&<div className={styles.empty}>표시할 회원이 없습니다.</div>}</div>}
